'use client';
import { Document, Page, Text, View, Image, StyleSheet, Font } from '@react-pdf/renderer';

// Create styles (like CSS but for PDFs)
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    color: '#ea580c', // Orange color
    fontWeight: 'bold',
  },
  image: {
    width: '100%',
    height: 300,
    objectFit: 'contain',
    marginBottom: 20,
    borderRadius: 8,
  },
  text: {
    fontSize: 12,
    lineHeight: 1.5,
    marginBottom: 10,
    color: '#374151',
    fontFamily: 'Helvetica',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#9ca3af',
  },
});

// The Component that renders the PDF
export const StoryPDF = ({ story, imageUrl, title }: { story: string; imageUrl: string; title: string }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        
        {/* Only show image if we have one */}
        {imageUrl && (
          <Image 
            src={imageUrl} 
            style={styles.image} 
          />
        )}
        
        <Text style={styles.text}>
          {story}
        </Text>

        <Text style={styles.footer}>
          Generated by SparkTales ✨
        </Text>
      </Page>
    </Document>
  );
};